### ISSUE TITLE
Core dumped on ubuntu18.04 currently.

### ISSUE THREAD

**Issue by suijingfeng** [Jiboo/libhut#1]
logs as follows:

[DebugReport] Object: 0x562f35115a10 (Type = 28) | Added callback
[DebugReport] Object: 0x562f35115a10 (Type = 28) | Added callback
[DebugReport] Object: 0x562f35115a10 (Type = 28) | Added callback
[DebugReport] Object: 0x562f35115a10 (Type = 28) | Added callback
[DebugReport] Object: 0x562f35115a10 (Type = 28) | Added callback
[174.1] initialized display
[211.5] initialized window
[211.8] initialized buffer
[266.0] initialized pipelines
[266.7] allocated buffers
[266.7] copied data
[Validation]  [ VUID-VkWriteDescriptorSet-descriptorType-00327 ] Object: VK_NULL_HANDLE (Type = 2) | vkUpdateDescriptorSets(): pDescriptorWrites[0].pBufferInfo[0].offset (0xc0) must be a multiple of device limit minUniformBufferOffsetAlignment 0x100. The spec valid usage text states 'If descriptorType is VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER or VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, the offset member of each element of pBufferInfo must be a multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-00327)
[267.6] initialized image
[Validation]  [ VUID-VkSamplerCreateInfo-anisotropyEnable-01070 ] Object: VK_NULL_HANDLE (Type = 0) | vkCreateSampler(): Anisotropic sampling feature is not enabled, pCreateInfo->anisotropyEnable must be VK_FALSE. The spec valid usage text states 'If the anisotropic sampling feature is not enabled, anisotropyEnable must be VK_FALSE' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkSamplerCreateInfo-anisotropyEnable-01070)
[268.4] initialized sampler
[268.4] started image load thread
[268.5] finished callback setup
[268.5] single job
[270.3] drawing...
[270.4] drawn
fps: 2
[Validation]  [ VUID-vkBeginCommandBuffer-commandBuffer-00049 ] Object: 0x562f35128fc8 (Type = 6) | Calling vkBeginCommandBuffer() on active command buffer 562f35128fc8 before it has completed. You must check command buffer fence before this call. The spec valid usage text states 'commandBuffer must not be in the recording or pending state.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkBeginCommandBuffer-commandBuffer-00049)
[30278.3] done loading texture
[[Validation]  [ VUID-VkWriteDescriptorSet-descriptorType-00327 ] Object: VK_NULL_HANDLE (Type = 2) | vkUpdateDescriptorSets(): pDescriptorWrites[0].pBufferInfo[0].offset (0x180) must be a multiple of device limit minUniformBufferOffsetAlignment 0x100. The spec valid usage text states 'If descriptorType is VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER or VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, the offset member of each element of pBufferInfo must be a multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-00327)
30278.3] drawing...
[Validation]  [ VUID-VkWriteDescriptorSet-descriptorType-00327 ] Object: VK_NULL_HANDLE (Type = 2) | vkUpdateDescriptorSets(): pDescriptorWrites[0].pBufferInfo[0].offset (0x240) must be a multiple of device limit minUniformBufferOffsetAlignment 0x100. The spec valid usage text states 'If descriptorType is VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER or VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, the offset member of each element of pBufferInfo must be a multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-00327)
[30278.4] bound tex pipelines
[30278.5] drawn
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to submit draw command buffer!
Aborted (core dumped)

**Comment by Jiboo** [comment]
Hey,

Thanks for trying this out, although it is hardly usable, and more a training for me than a real project.
If you need a UI library I suggest looking elsewhere.

Does vulkan samples, like `vulkan-cube` works on your system? Could you do a gist with a `vulkaninfo` dump?

Thanks,
JB.

**Comment by suijingfeng** [comment]
Yes, I search xcb mouse and keyboard related code on github, and accident to your project.
![Screenshot](https://user-images.githubusercontent.com/10341056/60040968-c4388f00-96ec-11e9-979a-893476613ad1.png)

[Edit @Jiboo: Removed vulkaninfo for clarity]

**Comment by Jiboo** [comment]
If you have time to spare, would you mind testing this again with the recent commits?
Could you send a backtrace of the sigsegv? (either gdb or valgrind would do), using pastebin ;)

**Comment by suijingfeng** [comment]
Thanks to you, but i don't know how to Find HarfBuzz library ...
```
CMake Error at CMakeLists.txt:34 (find_package):
  By not providing "FindHarfBuzz.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "HarfBuzz",
  but CMake did not find one.

  Could not find a package configuration file provided by "HarfBuzz" with any
  of the following names:

    HarfBuzzConfig.cmake
    harfbuzz-config.cmake

  Add the installation prefix of "HarfBuzz" to CMAKE_PREFIX_PATH or set
  "HarfBuzz_DIR" to a directory containing one of the above files.  If
  "HarfBuzz" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by Jiboo** [comment]
The libharfbuzz-dev package from Ubuntu repos doesn't include a cmake configuration (harfbuzz-config.cmake) that the fedora package has, I didn't expect that. Thanks anyway, I'll try to fix that later.

**Comment by suijingfeng** [comment]
yes, working at fedora 30!
